INSERT INTO `{prefix}brands` (`name`, `bCat`, `enBrand`, `rwslug`) VALUES
('Canon', '1', 'yes', ''),
('Nikon', '1', 'yes', ''),
('Pentax', '1', 'yes', ''),
('LG', '2', 'yes', ''),
('Sony', '2', 'yes', ''),
('Panasonic', '2', 'yes', ''),
('Lenovo', '3', 'yes', ''),
('Asus', '3', 'yes', ''),
('Apple', '3', 'yes', ''),
('Tom Tom', '4', 'yes', ''),
('Garmin', '4', 'yes', ''),
('Noza', '4', 'yes', ''),
('Wileyfox', '5', 'yes', ''),
('Motorola', '5', 'yes', ''),
('Samsung', '5', 'yes', ''),
('Maxima', '6', 'yes', ''),
('V-Fit', '6', 'yes', ''),
('Ultrasport', '6', 'yes', ''),
('Muddyfox', '7', 'yes', ''),
('BMX', '7', 'yes', ''),
('Falcon', '7', 'yes', ''),
('Fitbit', '8', 'yes', ''),
('GoPro', '8', 'yes', ''),
('Coosa', '8', 'yes', ''),
('Milestone', '9', 'yes', ''),
('Mountaintop', '9', 'yes', ''),
('Readybed', '9', 'yes', ''),
('Bosch', '10', 'yes', ''),
('Numatic', '10', 'yes', ''),
('Keter', '11', 'yes', ''),
('Tepro', '11', 'yes', ''),
('New Age', '12', 'yes', ''),
('Japanese Music', '12', 'yes', ''),
('New Look', '13', 'yes', ''),
('Levi', '13', 'yes', ''),
('Lyle & Scott', '13', 'yes', ''),
('Under Armour', '13', 'yes', ''),
('Coast', '14', 'yes', ''),
('Esprit', '14', 'yes', ''),
('Canterbury', '14', 'yes', ''),
('Horror', '15', 'yes', ''),
('Thriller', '15', 'yes', ''),
('Animated', '15', 'yes', ''),
('Action', '15', 'yes', ''),
('Bosch', '11', 'yes', ''),
('Pro Breeze', '10', 'yes', '')