INSERT INTO `{prefix}categories` (`catname`, `titleBar`, `comments`, `catLevel`, `childOf`, `metaDesc`, `metaKeys`, `enCat`, `orderBy`, `enDisqus`, `freeShipping`, `imgIcon`, `showRelated`, `rwslug`, `theme`, `vis`) VALUES
('Cameras & Photography', '', '', 2, 16, '', '', 'yes', 1, 'no', 'no', '', 'yes', '', '', '1'),
('Televisions', '', '', 2, 16, '', '', 'yes', 5, 'no', 'no', '', 'yes', 'televisions', '', '1'),
('Laptops', '', '', 2, 16, '', '', 'yes', 2, 'no', 'no', '', 'yes', '', '', '1'),
('Sat Navs', '', '', 2, 16, '', '', 'yes', 4, 'no', 'no', '', 'yes', '', '', '1'),
('Mobile Phones', '', '', 2, 16, '', '', 'yes', 3, 'no', 'no', '', 'yes', '', '', '1'),
('Fitness', '', '', 2, 19, '', '', 'yes', 2, 'no', 'no', '', 'yes', '', '', '1'),
('Cycling', '', '', 2, 19, '', '', 'yes', 1, 'no', 'no', '', 'yes', '', '', '1'),
('Sports Technology', '', '', 2, 19, '', '', 'yes', 3, 'no', 'no', '', 'yes', '', '', '1'),
('Camping & Hiking', '', '', 1, 0, '', '', 'yes', 1, 'no', 'no', 'demo_icon_9.jpg', 'yes', '', '', '1'),
('Home & Kitchen', '', '', 1, 0, '', '', 'yes', 6, 'no', 'no', 'demo_icon_10.jpg', 'yes', '', '', '1'),
('Garden & Outdoors', '', '', 1, 0, '', '', 'yes', 4, 'no', 'no', 'demo_icon_11.jpg', 'yes', '', '', '1'),
('Music', '', '', 2, 18, '', '', 'yes', 2, 'no', 'no', '', 'yes', '', '', '1'),
('Mens Clothes', '', '', 2, 17, '', '', 'yes', 1, 'no', 'no', '', 'yes', '', '', '1'),
('Womens Clothes', '', '', 2, 17, '', '', 'yes', 2, 'no', 'no', '', 'yes', '', '', '1'),
('Movies', '', '', 2, 18, '', '', 'yes', 1, 'no', 'no', '', 'yes', '', '', '1'),
('Technology', '', '', 1, 0, '', '', 'yes', 7, 'no', 'no', 'demo_icon_16.jpg', 'yes', '', '', '1'),
('Fashion', '', '', 1, 0, '', '', 'yes', 2, 'no', 'no', 'demo_icon_17.jpg', 'yes', '', '', '1'),
('Entertainment', '', '', 1, 0, '', '', 'yes', 3, 'no', 'no', 'demo_icon_18.jpg', 'yes', '', '', '1'),
('Health & Sport', '', '', 1, 0, '', '', 'yes', 5, 'no', 'no', 'demo_icon_19.jpg', 'yes', '', '', '1'),
('Downloads', '', '', 2, 18, '', '', 'yes', 3, 'no', 'no', '', 'yes', '', '', '1')