INSERT INTO `{prefix}currencies` (`currency`, `rate`, `enableCur`, `curname`, `currencyDisplayPref`) VALUES
('USD', '0', 'no', 'US Dollar', ''),
('JPY', '0', 'no', 'Japanese Yen', ''),
('CZK', '0', 'no', 'Czech Koruny', ''),
('DKK', '0', 'no', 'Danish Kroner', ''),
('GBP', '0', 'yes', 'British Pound', '&pound;{PRICE}'),
('HUF', '0', 'no', 'Hungarian Forint', ''),
('LTL', '0', 'no', 'Lithuanian Litai', ''),
('LVL', '0', 'no', 'Latvian Lati', ''),
('PLN', '0', 'no', 'Polish Zlotych', ''),
('SEK', '0', 'no', 'Swedish Kronor', ''),
('CHF', '0', 'no', 'Swiss Franc', ''),
('NOK', '0', 'no', 'Norwegian Krone', ''),
('HRK', '0', 'no', 'Croatian Kuna', ''),
('RUB', '0', 'no', 'Russian Rubles', ''),
('TRY', '0', 'no', 'Turkish New Lira', ''),
('AUD', '1.84', 'no', 'Australian Dollar', ''),
('BRL', '0', 'no', 'Brazilian Real', ''),
('CAD', '0', 'no', 'Canadian Dollar', ''),
('CNY', '0', 'no', 'Chinese Yuan Renminbi', ''),
('HKD', '11.00', 'no', 'Hong Kong Dollar', 'HKD{PRICE}'),
('IDR', '0', 'no', 'Indonesian Rupiah', ''),
('ILS', '0', 'no', 'Israeli Shekel', ''),
('INR', '0', 'no', 'Indian Rupee', ''),
('KRW', '0', 'no', 'South Korean Won', ''),
('MXN', '0', 'no', 'Mexican Peso', ''),
('MYR', '0', 'no', 'Malaysian Ringgit', ''),
('NZD', '0', 'no', 'New Zealand Dollar', ''),
('PHP', '0', 'no', 'Philippine Peso', ''),
('SGD', '0', 'no', 'Singapore Dollar', ''),
('THB', '0', 'no', 'Thai Baht', ''),
('ZAR', '0', 'no', 'South African Rand', ''),
('EUR', '1.26', 'no', 'Euro', '{PRICE}&euro;'),
('NGN', '0', 'no', 'Nigerian Naira', '')